FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

COPY prisma ./prisma/
RUN yarn prisma generate

EXPOSE 8000

CMD ["sh", "-c", "npx prisma migrate dev && yarn prisma db seed && yarn dev"]
