# Dockerfile.dev

FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Install nodemon for auto-reload
RUN npm install -g nodemon

# Expose the development port
EXPOSE 3000

CMD ["npm", "run", "dev"]
