version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-exchange-backend
    ports:
      - "${PORT}:3000"
    environment:
      - DB_HOST=${DB_HOST_ENV}
      - DB_PORT=${DB_PORT_ENV}
      - DB_USER=${DB_USER_ENV}
      - DB_PASS=${DB_PASS_ENV}
      - DB_NAME=${DB_NAME_ENV}
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: book-exchange-db
    ports:
      - "${DB_PORT_ENV}:5432"
    environment:
      POSTGRES_USER: ${DB_USER_ENV}
      POSTGRES_PASSWORD: ${DB_PASS_ENV}
      POSTGRES_DB: ${DB_NAME_ENV}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
