version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "${PORT}:8000"
    environment:
      DATABASE_URL: postgres://${DB_USER_ENV}:${DB_PASS_ENV}@postgres:${DB_PORT_ENV}/${DB_NAME_ENV}
      PRISMA_DATABASE_URL: postgres://${DB_USER_ENV}:${DB_PASS_ENV}@postgres:${DB_PORT_ENV}/${DB_NAME_ENV}
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    container_name: swap-a-book-db
    ports:
      - "${DB_PORT_ENV}:5432"
    environment:
      POSTGRES_USER: ${DB_USER_ENV}
      POSTGRES_PASSWORD: ${DB_PASS_ENV}
      POSTGRES_DB: ${DB_NAME_ENV}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
